#define TOK_STATIC                          1
#define TOK_CONST                           2
#define TOK_IS                              3
#define TOK_KEYWORDOR                       4
#define TOK_PLUS                            5
#define TOK_MINUS                           6
#define TOK_OR                              7
#define TOK_STAR                            8
#define TOK_SLASH                           9
#define TOK_PERCENT                        10
#define TOK_AND                            11
#define TOK_LBRACKET                       12
#define TOK_LPAREN                         13
#define TOK_DOT                            14
#define TOK_NOT                            15
#define TOK_ELSE                           16
#define TOK_IF                             17
#define TOK_NEWLINE                        18
#define TOK_SEMICOLON                      19
#define TOK_LBRACE                         20
#define TOK_RBRACE                         21
#define TOK_CLASS                          22
#define TOK_IDENT                          23
#define TOK_COLON                          24
#define TOK_RPAREN                         25
#define TOK_INTERFACE                      26
#define TOK_MIXIN                          27
#define TOK_EQUALS                         28
#define TOK_COMMA                          29
#define TOK_SWITCH                         30
#define TOK_CASE                           31
#define TOK_FOR                            32
#define TOK_FOREACH                        33
#define TOK_FOREVER                        34
#define TOK_LOOP                           35
#define TOK_WHILE                          36
#define TOK_DO                             37
#define TOK_UNTIL                          38
#define TOK_TRY                            39
#define TOK_CATCH                          40
#define TOK_THROW                          41
#define TOK_INT                            42
#define TOK_FLOAT                          43
#define TOK_TRUE                           44
#define TOK_FALSE                          45
#define TOK_RBRACKET                       46
#define TOK_RETURN                         47
